### ISSUE TITLE
Improvement on Settings -> Permalinks tab

### ISSUE THREAD

**Issue by garyc40** [wp-e-commerce/wpec-theme-engine-v2#16]
- [x] Rename Permalinks tab to Pages
- [x] Remove "Current Settings" section
- [x] Auto-resize slug fields, with in-place sanitization
- [x] Add a new form section for page titles
- [x] "Save Changes" button beneath each page titles

Feedback is welcome.

![store settings wpec test site wordpress 2013-06-20 01-35-01](https://f.cloud.github.com/assets/52500/676031/3ed91bca-d8fe-11e2-801a-33549cafaa45.png)

**Comment by instinct** [comment]
Nice work!!!!

Without me first knowing that there is a Login Page or Password reminder page created by WP e-Commerce Plugin in the first place I'm wondering if "Leaving this field blank will disable the page" could be tweaked ever so slightly? I'm not sure what. I need another coffee first. Just a hunch. 

Should the Page Titles read "Corresponding Page Titles"? (am I being too pedantic?)

I feel like I really want to use this Gary!!!
