### ISSUE TITLE
Replacement for [add_to_cart=ID] shortcode?

### ISSUE THREAD

**Issue by jjeaton** [wp-e-commerce/wpec-theme-engine-v2#21]
Will the Theme Engine v2 have a replacement for the `add_to_cart` shortcode in v1?

I'm building a plugin that will integrate with WPEC and I need to add an add to cart button outside of a single product page or archive, and want to support the v2 theme engine.

The shortcode I'm referring to is: `add_to_cart_shortcode` in `/wpsc-components/theme-engine-v1/helpers/ajax.php`

**Comment by instinct** [comment]
Yes it will.

**Comment by instinct** [comment]
Is this done / can it be closed?

**Comment by jjeaton** [comment]
The shortcode is there now `[wpsc-add-to-cart]`. Is there an argument to have it not use the quantity field, and just display an add to cart button like the old shortcode (defaulting to a quantity of 1)?

**Comment by instinct** [comment]
That would be good wouldnt it... @garyc40 would need to respond to this though. I'm not sure.

**Comment by jjeaton** [comment]
If the answer is just to hide the quantity field with CSS, that's fine too.

I'm guessing having just the button would only work for simple products, as variations would need to be selected from drop-downs to get the add to cart to work, so maybe having just the button isn't the best approach...

**Comment by instinct** [comment]
Lots of products don't have variations though.

**Comment by jjeaton** [comment]
So, hiding the quantity field with CSS is easy enough to do. It's really just a nice-to-have if there were an attribute on the shortcode to `show_only_button=true` or something. The add to cart shortcode is there, so this can be closed.
