### ISSUE TITLE
missing label for the state field in checkout

### ISSUE THREAD

**Issue by instinct** [wp-e-commerce/wpec-theme-engine-v2#22]
This is come from support team :)

http://dl.dropboxusercontent.com/u/151891/screenshots/2013-07-18_1630.png

**Comment by garyc40** [comment]
This is a WPEC core issue, not new theme engine's issue.

I think I and Michelle had a chat about this back in the day. This is a deliberate decision by the 3.8 developers, it's in the code. The real State field is being hidden (or not even output). The state field instead is attached to the country field when that country has states. When there's not, the normal state field will appear.

Fixing this behavior is not easy and is error-prone, so we decided to just leave it alone.
