### ISSUE TITLE
Cart/checkout/account pages 'Nothing Found'

### ISSUE THREAD

**Issue by jjeaton** [wp-e-commerce/wpec-theme-engine-v2#24]
After installing the theme engine v2, I can't access the cart, checkout or account pages.

When I navigate to http://www.site.dev/store/cart I get a 404, or I guess what's happening is it's loading the `index.php` and displaying `Nothing found` where the content should go. Using debug bar, I see these query vars are set:

```
wpsc_controller=cart&wpsc_controller_args=
```

I'm running: 

WP 3.6-RC1-24757
WP e-Commerce 3.8.13-dev (clone of latest master branch)

I've tried resaving/changing permalinks (I wasn't using default), re-saving the 'Pages'  settings tab, but I can't seem to get these urls to work. Am I missing a configuration step?

**Comment by agusmu** [comment]
it happens to me too... still trying to check the code...

**Comment by jjeaton** [comment]
Thanks! This solved it for me.
