### ISSUE TITLE
install / upgrade screen (text + image preview) 

### ISSUE THREAD

**Issue by instinct** [wp-e-commerce/wpec-theme-engine-v2#25]
This is just a first round attempt for getting text and image positioning correct. We'll nail the text and the images internally and feed it through to developers accordingly.

**New Theme Engine**

The new WP e-Commerce has stripped back its legacy theme engine and build a beautiful brand spanking new one that just works with any Theme! 

Our new Theme engine implementation has been inspired by how bbPress and BuddyPress handle Themeing, therefore WordPress Theme creators will find it very similar and familiar. We believe that our new found efforts in this space make WP e-Commerce Plugin the most WordPress Theme friendly e-Commerce Plugin around. 

Going forward we will be producing and releasing new WordPress e-Commerce Themes
built using the underscores.me theme framework. Why? Because the whats good enough for WordPress is good enough for WP e-Commerce Plugin. 

Stay tuned as our strategy unfolds...

**Integrated marketplace**

For store owners and developers.

Shop owners can rejoice because they can now easily find all their e-Commerce needs in the one place. From Themes to Plugins everything you might want for your store is right here in WP e-Commerce. 

Developers who want to sell in our marketplace can do so easily, simply connect your 
products in your git repo with our shop and  you’re ready to sell. Learn More!

![install-update](https://f.cloud.github.com/assets/917424/1424887/497e01ee-4028-11e3-9958-33e4867835de.jpg)

**Comment by JustinSainton** [comment]
Superceded by https://github.com/wp-e-commerce/WP-e-Commerce/issues/618.  Has a PR, but far from ready for primetime.
