### ISSUE TITLE
Fetal error on WP 3.7.1

### ISSUE THREAD

**Issue by lijinma** [wp-e-commerce/wpec-theme-engine-v2#26]
When i activate the plugin, the error occurs as follow:

Fatal error: Call to undefined function wpsc_register_post_types() in /wordpress/wp-content/plugins/wpec-theme-engine-v2/wp-e-commerce-theme-engine-v2.php on line 28
Call Stack

``` sh
0   Time    Memory  Function    Location
1   0.0028  940840  {main}( )   ../plugins.php:0
2   0.5929  44455992    do_action( )    ../plugins.php:150
3   0.5929  44457592    call_user_func_array ( )    ../plugin.php:429
4   0.5929  44457624    _wpsc_te_v2_activate( ) ../plugin.php:429
```

Have no idea of what's going on.

Thanks a lot.

**Comment by garyc40** [comment]
Hi @lijinma ,

Did you enable WP e-Commerce plugin? This theme engine requires WP e-Commerce 3.8.13-dev to be activated first.

I'll work on a more proper error message, but for now make sure WP e-Commerce is enabled. Download the WP e-Commerce 3.8.13-dev (not ready for production) release here: https://github.com/wp-e-commerce/WP-e-Commerce/archive/master.zip

**Comment by lijinma** [comment]
Hi @garyc40  thank you for your answer.

It's my fault, I didn't WP e-Commerce.
