### ISSUE TITLE
Title broken on store page

### ISSUE THREAD

**Issue by leewillis77** [wp-e-commerce/wpec-theme-engine-v2#4]
Installing on a fresh WP install, I get the following <title> tags on normal pages / posts:

%page/post name% | %site name%

E.g. 

Hello World! | WordPress Test Site

On the store page however I get

Store | 

ie the site name is missing.

**Comment by garyc40** [comment]
Yes I have this issue as well. Working on a fix.

**Comment by garyc40** [comment]
PR #7 fixed it for me. Please test.
