### ISSUE TITLE
Sale prices shown incorrectly

### ISSUE THREAD

**Issue by leewillis77** [wp-e-commerce/wpec-theme-engine-v2#9]
The "sale price" box on products can't be empty (Which is probably a whole separate issue on WPEC core, but still ...). 

Setup a product as follows:
Price: 4.00
Sale price: 0.00

On standard WP e-Commerce this shows up as a product priced at 4.00. 

On an install with the new theme engine the product page shows as if the product is on sale, ie

Old price: 4.00
Price: 0.00
You Save: 4.00

I've not confirmed whether this price carries through to the cart due to #8

**Comment by benhuson** [comment]
I guess that needs to be fixed to work as current.

But yes, I think you should be able to have an empty sale field or enter 0 for 100% discount - Can see the possibility of people maybe wanting to offer free downloads for a period of time etc
